#!/usr/bin/env node
/**
 * GENERATED by `citarium mirror` — do not edit.
 *
 * Fetch this instance's published corpus so `citarium-mcp` can serve the
 * same bytes https://agentreliability.dev serves. Every path below is public.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ORIGIN = process.env["CITARIUM_ORIGIN"] ?? "https://agentreliability.dev";
const OUT = process.env["CITARIUM_BUILD_DIR"] ?? "./corpus";

async function grab(path, { optional = false } = {}) {
  const res = await fetch(`${ORIGIN}/${path}`);
  if (!res.ok) {
    if (optional) return null;
    throw new Error(`${path} → ${res.status}`);
  }
  return res.text();
}

function put(path, body) {
  const target = join(OUT, path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, body);
}

for (const path of ["ai-index.json","api/index.json","api/sources.json","llms-full.txt"]) {
  put(path, await grab(path));
}
for (const path of ["api/media.json"]) {
  const body = await grab(path, { optional: true });
  if (body !== null) put(path, body);
}

const ids = JSON.parse(await grab("api/index.json")).map((o) => o.id);
let next = 0;
await Promise.all(
  Array.from({ length: 8 }, async () => {
    while (next < ids.length) {
      const id = ids[next++];
      put(`api/k/${id}.json`, await grab(`api/k/${id}.json`));
    }
  }),
);
console.log(`fetched ${ids.length} objects from ${ORIGIN} into ${OUT}`);
